version: "2"
run:
  timeout: 3m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0