@startuml
' skinparam
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName "Arial"
skinparam defaultFontSize 12
skinparam roundCorner 5
skinparam sequence {
    ActorBorderColor Black
    LifeLineBorderColor Black
    ParticipantBorderColor Black
    ArrowColor Black
}

actor Client
participant "cosemObject:Data" as CosemObject
participant "baseImpl:BaseImpl" as BaseImpl

Client -> CosemObject: SetAttribute(attributeID, value)
activate CosemObject
CosemObject -> BaseImpl: SetAttribute(attributeID, value)
activate BaseImpl
BaseImpl -> BaseImpl: PreWriteCallback(attributeID, value, ctx)
BaseImpl -> BaseImpl: PostWriteCallback(attributeID, value, ctx)
BaseImpl --> CosemObject: error
deactivate BaseImpl
CosemObject --> Client: error
deactivate CosemObject
@enduml
